#!/usr/bin/perl -w

use strict;

use 5.10.1;

say "Checking the number <$ARGV[0]>";

given($ARGV[0]) {
    
    when(! /\A\d+\Z/) {say "Not a number!"}
    
    my @divisors = &divisor($_);
    
    when(2 ~~ @divisors) { # 2 is in @divisors
        say "$_ is even";
        continue;
    }
    
    when(! (2 ~~ @divisors)) { # 2 isn't in @divisors
        say "$_ is odd";
        continue;
    }

    say "What is your favorite number?";
    chomp(my $favorite = <STDIN>);
    when($favorite ~~ @divisors) {
        say "$_ is divisible by my favorite number";
        continue;
    }

    when($favorite) { # $_ ~~ favorite
        say "$_ is my favorite number";
        continue;
    }

    when(@divisors ~~ []) {say "The number is a prime"; continue}
    
    default {say "$_ is divisible by @divisors"}
   }

sub divisor{
    my $number = shift;
    my @divisors = ();
    foreach my $divisor ( 2.. ($ARGV[0]/2 + 1)) {
        push @divisors, $divisor unless $number % $divisor;
    }
    return @divisors;
}
