#!/usr/bin/perl -w

use strict;

use 5.10.1;

my $Verbose = $ENV{VERBOSE} // 1;

my $secret = int(1 + rand 100);

#print "Don't tell anyone, but the secret number is $secret.\n" if $Verbose;

LOOP: {
    print "Please enter a guess from 1 to 100: ";
    chomp (my $guess = <STDIN>);

    my $found_it = 0;

    given($guess) {
        when(!/\A\d+\Z/) {say "Not a number!"}
        when($_ > $secret) {say "Too High!"}
        when($_ < $secret) {say "Too low!"}
        default {say "Just right!"; $found_it++}
    }

    last LOOP if $found_it;
    redo LOOP;
}
