#!/usr/bin/perl -w

use strict;

use 5.10.1;

say "Checking the number <$ARGV[0]>";

given($ARGV[0]) {
    when(! /\A\d+\Z/) {say "Not a number!"}
    my @divisors = &divisor($_);
    when(@divisors ~~ []) {say "The number is a prime"}
    default {say "$_ is divisible by @divisors"}
}

sub divisor{
    my $number = shift;
    my @divisors;
    for(2..$number/2) {
        push @divisors, $_ unless $number % $_;
    }
    return @divisors;
}
