#!/usr/bin/perl

use 5.014;

my @fred = above_average(1..10);
print "\@fred is @fred\n";
print "(Should be 6 7 8 9 10)\n";
my @barney = above_average(100, 1..10);
print "\@barney is @barney\n";
print "(Should be just 100)\n";

sub above_average {
    my @above_list;
    my $average = &average(@_);
    foreach(@_) {
        if($_>$average) {
            push @above_list, $_;
        }
    }
    @above_list;
}

sub average {
    if(@_ == 0) {return}
#    my $count = @_;
#    my $sum = &total(@_);
    return &total(@_)/@_;
}

sub total {
    my $sum = 0;
    foreach (@_) {
        $sum += $_;
    }
    return $sum;
}
