#!/usr/bin/perl

use strict;
use warnings;

if(! open MYFILE, "input.txt") {
    die "Cannnot open input file: $!";
}

while(<MYFILE>) {
    chomp;
    if(/(^|\p{Space}+)[fF]red($|\p{Space}+)/) {
        print $_ . "\n";
    }
}
