#!/usr/bin/perl

use strict;
use warnings;

if(! open MYFILE, "input.txt") {
    die "Cannnot open input file: $!";
}

while(<MYFILE>) {
    chomp;
    if(/(((^|\p{Space}+)wilma\p{Space}+).*(\p{Space}+fred($|\p{Space}+)))|(((^|\p{Space}+)fred\p{Space}+).*(\p{Space}+wilma($|\p{Space}+)))/) {
        print $_ . "\n";
    }
}
