#!/usr/bin/perl

use 5.010;

greet("Fred");
greet("Barney");
greet("Wilam");
greet("Betty");

sub greet {
    my ($name) = @_;
    state @names;
    if($#names == -1) {
        print "Hi $name! You are the first one here!\n";
    } else {
        print "Hi $name! I've seen: @names\n";
    }
    push @names, $name;
}
