#!/usr/bin/perl

use warnings;

foreach my $filename (reverse(@ARGV)) {
    if(! open MYFILE, $filename) {
        warn "Cannot open file $filename: $!";
    } else {
        print reverse <MYFILE>;
    }
    close MYFILE;
}
