#!/usr/bin/perl

use 5.010;

greet("Fred");
greet("Barney");
greet("Wilma");
greet("Betty");

sub greet {
    my ($name) = @_;
    state $last;
    if(defined $last) {
        print "Hi $name! $last is also here!\n";
    } else {
        print "Hi $name! You are the first one here!\n";
    }
    $last = $name;
}
