#!/usr/bin/perl

use strict;
use warnings;

if(! open MYFILE, "input.txt") {
    die "Cannnot open input file: $!";
}

while(<MYFILE>) {
    chomp;
    if(/(\S)\1/) {
        print $_ . "\n";
    }
}
